### ISSUE TITLE
"friends" command (similar to "followers")

### ISSUE THREAD

**Issue by simonw** [dogsheep/twitter-to-sqlite#31]
Current list of commands:
```
  followers          Save followers for specified user (defaults to...
  followers-ids      Populate followers table with IDs of account followers
  friends-ids        Populate followers table with IDs of account friends
```
Obvious omission here is `friends`, which would be powered by `https://api.twitter.com/1.1/friends/list.json`: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list

**Comment by simonw** [comment]
Command still needs documentation and a bit more testing.

**Comment by dckc** [comment]
yay! Thanks a bunch for the `twitter-to-sqlite friends` command!

The twitter "Download an archive of your data" feature doesn't include who I follow, so this is particularly handy.

The whole Dogsheep thing is great :) I've written about similar things under [cloud-services](https://www.madmode.com/search/label/cloud-services/):
 - 2021: [Closet Librarian Approach to Cloud Services](https://www.madmode.com/2021/closet-librarian-approach-cloud-services.html)
 - 2015: [jukekb \- Browse iTunes libraries and upload playlists to Google Music](https://www.madmode.com/2015/jukekb)
