### ISSUE TITLE
Not all quoted statuses get fetched?

### ISSUE THREAD

**Issue by gsajko** [dogsheep/twitter-to-sqlite#56]
![image](https://user-images.githubusercontent.com/42315895/106259325-5f75dc80-621f-11eb-8311-db8f2fe2a257.png)

In my database I have 13300 quote tweets, but eta 3600 have `quoted_status` empty.

I fetched some of them using `https://api.twitter.com/1.1/statuses/show.json?id=xx` and they did have ids of quoted tweets.

**Comment by simonw** [comment]
This is interesting - how did you create that initial table? Was this using the `twitter-to-sqlite import archive.db ~/Downloads/twitter-2019-06-25-b31f2.zip` command, or something else?

**Comment by gsajko** [comment]
I think with `twitter-to-sqlite home-timeline home.db -a  auth.json --since`

**Comment by gsajko** [comment]
I figured it out.
Those tweets are in database, because somebody quote tweeted them, or retweeted them.
And if you grab quoted tweet or reweeted tweet from other tweet json, It doesn't grab all of the details.

So if someone quote tweeted a quote tweet, the second quote tweet won't have `quoted_status`.
